import pygame as pg
pg.init()
pg.mixer.init()
bullet_image = pg.image.load("../image/enemy/BULLET.png")
ground_image = pg.image.load("../image/background/ground.png")
wall_forest_image =pg.image.load("../image/background/wall_forest.png")
ldoor_image = pg.image.load("../image/background/door_left.png")
rdoor_image = pg.image.load("../image/background/door_right.png")
udoor_image = pg.image.load("../image/background/door_up.png")
ddoor_image = pg.image.load("../image/background/door_down.png")
heart_image = pg.image.load("../image/etc/Heart.png")
mob1_image = pg.image.load("../image/enemy/mob_01.png")
mob2_image = pg.image.load("../image/enemy/mob_02.png")
skill1_1_0_image = pg.image.load("../image/skill/skill1_1_0.png")
skill1_1_1_image = pg.image.load("../image/skill/skill1_1_1.png")
skill1_1_2_image = pg.image.load("../image/skill/skill1_1_2.png")
skill1_1_3_image = pg.image.load("../image/skill/skill1_1_3.png")
skill1_2_image = pg.image.load("../image/skill/skill1_2.png")
player0_image = pg.image.load("../image/player/player.png")
player1_image = pg.image.load("../image/player/player.back.png")
player2_image = pg.image.load("../image/player/player.left.png")
player3_image = pg.image.load("../image/player/player.right.png")
back_music = pg.mixer.Sound('../sound/main.wav')
font_tvn = pg.font.Font("../font/tvn.ttf", 50)
